# Generated by Django 4.1.7 on 2024-03-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('class', '0002_workspace_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.workspace')),
            ],
            options={
                'unique_together': {('student', 'workspace')},
            },
        ),
    ]
