# Generated by Django 4.1.7 on 2024-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(null=True, upload_to='assignments/'),
        ),
    ]
