# Generated by Django 4.1.7 on 2024-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_assignment_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
