# Generated by Django 4.1.7 on 2024-03-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('class', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='student',
            field=models.ManyToManyField(related_name='s_room', through='class.Membership', to='profiles.student'),
        ),
    ]
