# Generated by Django 4.1.7 on 2024-03-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('class', '0004_assignment_created_at_assignment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.workspace')),
            ],
        ),
    ]
