# Generated by Django 4.1.7 on 2024-03-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_workspace_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='students',
        ),
    ]
