# Generated by Django 4.1.7 on 2024-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0008_remove_workspace_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
