<<<<<<< HEAD:plagiarism/classroom/migrations/0001_initial.py
# Generated by Django 5.0.3 on 2024-03-25 17:31
=======
# Generated by Django 4.1.7 on 2024-03-24 00:58
>>>>>>> d42dce137f2a1de0cadd37ae92488e6420719d11:plagiarism/class/migrations/0001_initial.py

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('points', models.IntegerField(null=True)),
                ('pdf', models.FileField(upload_to='assignments/')),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('stream', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('details', models.TextField()),
                ('students', models.ManyToManyField(blank=True, related_name='workspace', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='profiles.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
