# Generated by Django 5.0.3 on 2024-03-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='students',
        ),
    ]
