# Generated by Django 5.0.3 on 2024-03-25 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_workspace_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
